platform :ios, '8.0'
use_frameworks!

target 'StaticLib_Example' do
    pod 'StaticLib',:path => "/Users/romanovakov/Desktop/Libraries/StaticLib"
    #pod 'StaticLib',:path => "https://github.com/novacom34/StaticLib.git"
    pod 'Alamofire'
    
end
